# Numphy - Machine Learning

> Num - Numerical, Py - Python

> Most impt libraries in Python for numerical  computations.

> Backbone of ML in Python.

>They store data of similar datatypes only.

> Numphy consist of two parts:

>> ndarray: n-dimensional array

>>Ufunc: Universal functions

# ndarray


In [2]:
#How to create a numphy
import numpy as np
np.__version__

'1.20.1'

In [3]:
#in list we were allowed to save any data type
l = [1,2.3,"Mau",5-9j]
l

[1, 2.3, 'Mau', (5-9j)]

In [4]:
# in numpy array it has to be of same data type
#Create an array
#np.array(data, dtype)

arr = np.array([10,20,30,40,50], dtype = "int")
print(arr)
print(type(arr))
print(arr.dtype)

[10 20 30 40 50]
<class 'numpy.ndarray'>
int32


In [5]:
#without data type mentioned

arr = np.array([10,20,30,40,50])
print(arr)
print(type(arr))
print(arr.dtype)

[10 20 30 40 50]
<class 'numpy.ndarray'>
int32


In [6]:
#using different data type

arr = np.array([10,20,30.0,40,50])
print(arr)
#converts everything will be in float
print(type(arr))
print(arr.dtype)

[10. 20. 30. 40. 50.]
<class 'numpy.ndarray'>
float64


In [7]:
#add complex number

arr = np.array([10,20,30,40,9+6j,50])
#everything is converted to complex number
print(arr)
print(type(arr))
print(arr.dtype)

[10.+0.j 20.+0.j 30.+0.j 40.+0.j  9.+6.j 50.+0.j]
<class 'numpy.ndarray'>
complex128


In [17]:
#using string

arr = np.array([10,20,30,40,9+6j,50,"Mau"])
#everything is converted to String
print(arr)
print(type(arr))
print(arr.dtype)


['10' '20' '30' '40' '(9+6j)' '50' 'Mau']
<class 'numpy.ndarray'>
<U64


**Note:** which ever data has highest precidence it gets converted into that

In [8]:
#using functions

arr = np.array([10,20,30,40,50])
print(arr)
print(type(arr))
print(arr.dtype)
print(np.ndim(arr)) #dimension of the array
print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.median(arr))
print(np.var(arr)) #variance
print(np.std(arr)) #standard diviation - sq root of variance

#indexing operation
print(arr[0])
#slicing
print(arr[1:3]) #SI = 1, EI = 3-1

[10 20 30 40 50]
<class 'numpy.ndarray'>
int32
1
150
30.0
10
50
30.0
200.0
14.142135623730951
10
[20 30]


In [9]:
arr = np.array([10,20,30,40,9+6j,50,"Mau"])
#everything is converted to String
print(arr)
print(type(arr))
print(arr.dtype)
print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.median(arr))
print(np.var(arr)) #variance
print(np.std(arr)) #standard diviation




['10' '20' '30' '40' '(9+6j)' '50' 'Mau']
<class 'numpy.ndarray'>
<U64


TypeError: cannot perform reduce with flexible type

**NOTE:** with above observation **Numpy is used for numerical computaions. So  it would be baseless to if we store anything other than number in numpy array**

In [22]:
#using functions with 2D

arr = np.array([[10,20],[30,40],[50,60]])
print(arr)
print(type(arr))
print(arr.dtype)
print(np.ndim(arr)) #dimension of the array
print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.median(arr))
print(np.var(arr)) #variance
print(np.std(arr)) #standard diviation

#to know the no. of rows and columns
print(arr.shape)
#(3,2) - 3 rows and 2 columns


#indexing operation
print(arr[0])
print(arr[0][1])
#slicing
print(arr[1:3]) #SI = 1, EI = 3-1

[[10 20]
 [30 40]
 [50 60]]
<class 'numpy.ndarray'>
int32
2
210
35.0
10
60
35.0
291.6666666666667
17.07825127659933
(3, 2)
[10 20]
20
[[30 40]
 [50 60]]


In [23]:
np.zeros([2,4])
#create matrix of 2 rows and 4 columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.zeros([2,4], dtype="int")

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [25]:
np.ones([2,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
np.ones([12,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# Identity matrix

Square matrix

In [27]:
#np.identity([3,3]) no need to use these instead use
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [29]:
b = np.zeros_like(a)
b

array([[0, 0],
       [0, 0]])

In [30]:
c = np.ones_like(a)
c

array([[1, 1],
       [1, 1]])

In [31]:
#create random values of 3 rows and 4 columns
#Machine Learning
np.random.rand(3,4)

array([[0.9175688 , 0.6862827 , 0.87641562, 0.00265826],
       [0.59038513, 0.12786365, 0.26913888, 0.67042228],
       [0.2588278 , 0.84773972, 0.54270541, 0.89710279]])

# Time module

In [32]:
#current time
import time
time.time()

1632577209.0153675

In [33]:
for i in range(25):
    print(time.time(), end = " | ")

1632577209.1874475 | 1632577209.1874475 | 1632577209.1874475 | 1632577209.1874475 | 1632577209.1874475 | 1632577209.188399 | 1632577209.188399 | 1632577209.188399 | 1632577209.188399 | 1632577209.188399 | 1632577209.188399 | 1632577209.188399 | 1632577209.188399 | 1632577209.188399 | 1632577209.188399 | 1632577209.188399 | 1632577209.188399 | 1632577209.188399 | 1632577209.188399 | 1632577209.188399 | 1632577209.188399 | 1632577209.188399 | 1632577209.188399 | 1632577209.188399 | 1632577209.188399 | 

In [34]:
for i in range(25):
    print(time.time(), end = " | ")
    #Delay in time
    time.sleep(.2)

1632577209.3716846 | 1632577209.5725918 | 1632577209.7726095 | 1632577209.973362 | 1632577210.1742895 | 1632577210.3747137 | 1632577210.5755527 | 1632577210.7756102 | 1632577210.9846978 | 1632577211.1854336 | 1632577211.3862846 | 1632577211.586678 | 1632577211.7866824 | 1632577211.9867804 | 1632577212.187555 | 1632577212.3881083 | 1632577212.5882514 | 1632577212.7936504 | 1632577212.994657 | 1632577213.1977253 | 1632577213.4116504 | 1632577213.6266572 | 1632577213.8270266 | 1632577214.0275671 | 1632577214.2281826 | 

In [35]:
initial_time = time.time()
sum=0
for i in range(999999999):
    sum = sum+0
    
end_time = time.time()
print(end_time - initial_time)

95.57428741455078


# SPEED OF NUMPHY VS PYTHON

### Speciality of numphy

In [37]:
# importing required packages
import numpy
import time

# size of arrays and lists
size = 1000000

# declaring lists
list1 = range(size)
list2 = range(size)

# declaring arrays
#arange is going to genarate exactly same as range. 
#but these are numpy array list
array1 = numpy.arange(size)
array2 = numpy.arange(size)

# list
initialTime = time.time()
resultantList = [(a * b) for a, b in zip(list1, list2)]

# calculating execution time
print("Time taken by Lists :",
	(time.time() - initialTime),
	"seconds")

# NumPy array
initialTime = time.time()
resultantArray = array1 * array2

# calculating execution time
print("Time taken by NumPy Arrays :",
	(time.time() - initialTime),
	"seconds")


Time taken by Lists : 0.1426553726196289 seconds
Time taken by NumPy Arrays : 0.0019969940185546875 seconds


# **Why are numpy faster?**
- Numphy has vectoriezed function i.e. all of numpy fn body is written in C++.

In [38]:
#arange function in numpy

np.arange(12)

#range fn is there in pyhton


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [39]:
#Reshape function
a = np.arange(12)
a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [40]:
a.reshape(3,4)

#reshape the array in 3 rows and 4 columns

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
#simplified code
np.arange(12).reshape(3,4)

#multiplication of 3 and 4 is 12 so chose in such a way that the multiple of those rows and column is the size of the arange

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [43]:
np.arange(12).reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [44]:
np.arange(12).reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [45]:
np.arange(12).reshape(12,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [46]:
np.arange(12).reshape(1,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [47]:
np.arange(12).reshape(1,4)
#you will get error as size arange dsnt match with the multiple of reshape

ValueError: cannot reshape array of size 12 into shape (1,4)

In [10]:
#2 arrays of 2 rows and 3 columns
np.arange(12).reshape(2,2,3)


array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

# UFUNC

>It supports Broadcasting.

In [11]:
arr = np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [12]:
arr + 5

#every value is added with 5

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [13]:
#every value is multiplied with 2
arr * 2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [14]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
#Transpose of a Matrix
arr_t = arr.T
arr_t

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [16]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [ ]:
# Matrix Multiplication
# if 1st matrix is of order (m*p) the it will be multipled with order of (p*n) = (m*n)
#(m*p) * (p*n) = (m*n)

arr.dot(arr_t)

In [20]:
a = np.array([[7,5,-3],[3,-5,2],[5,3,-7]])
b = np.array([16,-8,0])
#linalg = linear algebra
np.linalg.solve(a,b)

array([1., 3., 2.])

In [21]:
#Inverse of matrix

y = np.array([[1,2],[3,4]])
np.linalg.inv(y)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [22]:
#Determinant of matrix
y = np.array([[1,2],[3,4]])
np.linalg.det(y)

-2.0000000000000004

# Pandas

Impt lib for Data Manipulation, Data Wrangling and Data Analysis

All data representation in panda is done in 2 primary data structures:

>Series: 1D nDarray with axis label

>DataFrame: 2D ndarray

# Series


In [71]:
import pandas as pd
pd.__version__


'1.2.4'

In [72]:
#Creating Dictionary
population = {
    "California" : 3546457657,
    "Texas" : 234534353,
    "New York" : 3495723094,
    "Florida" : 329579375,
    "Illinois" : 34957309
    
}
population

{'California': 3546457657,
 'Texas': 234534353,
 'New York': 3495723094,
 'Florida': 329579375,
 'Illinois': 34957309}

In [73]:
#pd.Series(data, index)
pd.Series([2,4,6])

0    2
1    4
2    6
dtype: int64

In [74]:
# giving user defined indexes
pd.Series([2,4,6], index = ['A','B','C'])

A    2
B    4
C    6
dtype: int64

In [75]:
pd.Series(population)

California    3546457657
Texas          234534353
New York      3495723094
Florida        329579375
Illinois        34957309
dtype: int64

In [76]:
s = pd.Series(population)
print(s)
print(type(s))
print()

print(s.index) #index is an attribute
print()

print(s.values) # only the values of list
print()

print(s.shape) # displays 5 values

California    3546457657
Texas          234534353
New York      3495723094
Florida        329579375
Illinois        34957309
dtype: int64
<class 'pandas.core.series.Series'>

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

[3546457657  234534353 3495723094  329579375   34957309]

(5,)


In [77]:
#Creating data frame
#pd.DataFrame(data, index=columns)
df = pd.DataFrame(s)
df

0
California  3546457657
Texas        234534353
New York    3495723094
Florida      329579375
Illinois      34957309

In [78]:
df.shape 
#5 rows and 1 column

(5, 1)

In [79]:
df.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [80]:
df.values

array([[3546457657],
       [ 234534353],
       [3495723094],
       [ 329579375],
       [  34957309]], dtype=int64)

In [81]:
df = pd.DataFrame(s)
print(df)
#if u use print the column looks not so good while executing a data frame

                     0
California  3546457657
Texas        234534353
New York    3495723094
Florida      329579375
Illinois      34957309


In [82]:
#naming the cloumn 
df = pd.DataFrame(s, columns = ["Population"])
df

Population
California  3546457657
Texas        234534353
New York    3495723094
Florida      329579375
Illinois      34957309

In [83]:
#How to get indexes
df = pd.DataFrame(s)
df

0
California  3546457657
Texas        234534353
New York    3495723094
Florida      329579375
Illinois      34957309

In [84]:
df.columns

RangeIndex(start=0, stop=1, step=1)

In [85]:
df.columns = ['Populations']
df

Populations
California   3546457657
Texas         234534353
New York     3495723094
Florida       329579375
Illinois       34957309

In [86]:
#indexs are california,texas .....
df.reset_index()
#indexs are shifted in dataframe

index  Populations
0  California   3546457657
1       Texas    234534353
2    New York   3495723094
3     Florida    329579375
4    Illinois     34957309

In [87]:
df
#original data frame isnt saved with the reset index

Populations
California   3546457657
Texas         234534353
New York     3495723094
Florida       329579375
Illinois       34957309

In [88]:
#Change original data frame
df = df.reset_index()
df

index  Populations
0  California   3546457657
1       Texas    234534353
2    New York   3495723094
3     Florida    329579375
4    Illinois     34957309

In [89]:
df.columns


Index(['index', 'Populations'], dtype='object')

In [90]:
df.columns = ['State','Population']
df

State  Population
0  California  3546457657
1       Texas   234534353
2    New York  3495723094
3     Florida   329579375
4    Illinois    34957309

In [91]:
#shift any column to index
df = df.set_index('Population')
df

State
Population            
3546457657  California
234534353        Texas
3495723094    New York
329579375      Florida
34957309      Illinois

In [92]:
df.columns

Index(['State'], dtype='object')

In [93]:
df.index

Int64Index([3546457657, 234534353, 3495723094, 329579375, 34957309], dtype='int64', name='Population')

In [94]:
df.values

array([['California'],
       ['Texas'],
       ['New York'],
       ['Florida'],
       ['Illinois']], dtype=object)

In [95]:
#create data frame from the scratch

df = pd.DataFrame({
    'Name': ["Maumita","Aditya","Siddhesh","Mohana"],
    "Salary" :[12000 , 10000, 2335, 23411]
})
df

Name  Salary
0   Maumita   12000
1    Aditya   10000
2  Siddhesh    2335
3    Mohana   23411

In [96]:
#in this data frame i want to select a particular column
df.Name

0     Maumita
1      Aditya
2    Siddhesh
3      Mohana
Name: Name, dtype: object

In [97]:
#select a particular column
df['Name']

0     Maumita
1      Aditya
2    Siddhesh
3      Mohana
Name: Name, dtype: object

In [98]:
#select a particular column
df.Salary

0    12000
1    10000
2     2335
3    23411
Name: Salary, dtype: int64

In [99]:
#select a particular column
df["Salary"]

0    12000
1    10000
2     2335
3    23411
Name: Salary, dtype: int64

In [100]:
df


Name  Salary
0   Maumita   12000
1    Aditya   10000
2  Siddhesh    2335
3    Mohana   23411

In [101]:
#Rename the column
df.columns = ["Emp Name","Salary"]
df

Emp Name  Salary
0   Maumita   12000
1    Aditya   10000
2  Siddhesh    2335
3    Mohana   23411

In [102]:
df.Emp Name
#if u have space then it wont be executed while coding

SyntaxError: invalid syntax (<ipython-input-102-a3b4e54197e5>, line 1)

In [103]:
df["Emp Name"]
#but this got executed

0     Maumita
1      Aditya
2    Siddhesh
3      Mohana
Name: Emp Name, dtype: object

# Read csv file


In [108]:
df = pd.read_csv("student_records.csv")
df

FileNotFoundError: [Errno 2] No such file or directory: 'student_records.csv'

In [109]:
df = pd.read_csv("https://raw.githubusercontent.com/ingledarshan/BoardInfinity/main/student_records.csv")
df

Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0   Henry            A        Y             90            85       Yes
1    John            C        N             85            51       Yes
2   David            F        N             10            17        No
3  Holmes            B        Y             75            71        No
4  Marvin            E        N             20            30        No
5   Simon            A        Y             92            79       Yes
6  Robert            B        Y             60            59        No
7   Trent            C        Y             75            33        No